### PR TITLE
Fix exception when running against master/3.6-dev

### PR DESCRIPTION
**Pull request by timmyc**
When running the latest master / 3.6-dev locally with this plugin installed, I was getting the following exception:

exception

This branch fixed the issue for me locally, but I'm unsure of _why_ the error was happening in the first place, but figured opening up a PR instead of an issue is always nice :)

### CODE REVIEW

**Review by claudiosanches — CHANGES_REQUESTED** [review]
We should load the REST API classes inside:

https://github.com/woocommerce/woocommerce-beta-tester/blob/a3fd1da1527876a7ed8b57dd97ac8ff42bd150af/includes/class-wc-beta-tester-admin-menus.php#L158-L161

This patch should only prevent errors, still it's required to load this data, at least once to be saved in the transient.

You can include the REST API classes with:


```php
if ( ! did_action( 'rest_api_init' ) ) {
	WC()->api->rest_api_includes();
}

if ( ! class_exists( 'WC_REST_System_Status_Controller', false ) ) {
	return '';
}
```

**Comment by timmyc** [comment]
Thanks for the review @claudiosanches - I updated the PR based on your feedback and verified the solution works ( much better ) than my original PR.

**Review by claudiosanches — APPROVED** [review]
LGTM!

**Comment by rodrigoprimo** [comment]
@claudiosanches @timmyc I believe there is a problem with the solution that was merged. WC_API::rest_api_includes() was originally a private method, and it was changed to public in WC 3.6. This means that users running WC < 3.6 running the new version of the beta tester plugin will get the following fatal error:

```
Fatal error: Uncaught Error: Call to private method WC_API::rest_api_includes() from context 'WC_Beta_Tester_Admin_Menus' in /srv/www/wc-beta-tester/htdocs/wp-content/plugins/woocommerce-beta-tester/includes/class-wc-beta-tester-admin-menus.php on line 161
```

I'm checking to see if I can find another way to include the class without using `WC_API::rest_api_includes()`.

**Pull request merged**
