### PR TITLE
Use WordPress.org for downloading WooCommerce

### PR DESCRIPTION
**Pull request by bor0**
With these changes, here's an example of how `zip_url` might look like:
```
- Eval of: '$this->config['zip_url']'

 ⬦ $this->config['zip_url'] = (string [65]) `https://downloads.wordpress.org/plugin/woocommerce.3.4.0-rc.2.zip`
```

We just need to make sure tags on .org are matching the names on GitHub.

### CODE REVIEW

**Review by kloon — DISMISSED** [review]
We should use the WP.org API for fetching the releases. https://api.wordpress.org/plugins/info/1.0/woocommerce.json Can use the versions array to find the matching version based on the selected option in the settings.

Full download urls are available through the API.

**Comment by bor0** [comment]
@kloon one more round please.

**Review by claudiosanches — APPROVED** [review]
I fixed a few coding standards issues and removed the `github_url`. All good now.

**Review by claudiosanches — DISMISSED** [review]
In fact there is still a problem with `get_latest_prerelease()`, the URL does not exists, and the method needs to be updated.

**Pull request merged**
